version: 0.0
os: linux
files:
  - source: /
    destination: Sentimental_Analyzer
hooks:
  BeforeInstall:
    - location: scripts/install_dependencies.sh
      timeout: 300
      runas: root
  AfterInstall:
    - location: scripts/start_server.sh
      timeout: 300
      runas: root
  ApplicationStart:
    - location: scripts/migrate_database.sh
      timeout: 300
      runas: root
