# Generated by Django 4.1.4 on 2022-12-29 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sentiment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='sentiment',
            field=models.CharField(default='', max_length=30),
        ),
    ]
